services:
  server:
    image: legiahoangthien/nestjs-backend:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mydb
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    image: legiahoangthien/react-frontend:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - server

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
